# Regressor

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 1 - Data Pre-Processing

## Importing the dataset

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Power_Plant.csv to Power_Plant.csv


In [3]:
import io
dataset = pd.read_csv(io.BytesIO(uploaded['Power_Plant.csv']), delimiter=",")

#dataset = pd.read_csv('Power_Plant.csv') # use it in VS Code

In [4]:
# list the dataset
dataset.head(10)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90
5  26.27  59.44  1012.23  58.77  443.67
6  15.89  43.96  1014.02  75.24  467.35
7   9.48  44.71  1019.12  66.43  478.42
8  14.64  45.00  1021.78  41.25  475.98
9  11.74  43.56  1015.14  70.72  477.50

## Spliting the data set into trainining and test sets

In [5]:
# First, divide the data set into independent (X) and dependent (y) variables
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
# Import the train_test_split function from the sklearn.model_selection module
from sklearn.model_selection import train_test_split

# Use train_test_split to split the data into training and testing sets
# X: Features, y: Target variable, test_size: Proportion of the dataset to include in the test split
# random_state: Seed for reproducibility, ensures the same split every time the code is run
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [8]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [9]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [10]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


# 2 - Modelling

## Training the Decision Tree Regression model on the test dataset

In [11]:
# Import the DecisionTreeRegressor model from the sklearn.tree module
from sklearn.tree import DecisionTreeRegressor

In [12]:
# A MODEL IS CREATED with parameters specific to the algorithm to be used.
# Here the name of the model is named "regressor".
regressor = DecisionTreeRegressor(random_state = 0)

## TRAIN the model with training data sets **(X_train and y_train)**.

In [13]:
# The model created above is TRAINED with the test dataset (X_train).
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

## Predicting the result
Get PREDICTIONS of the model using data from the test set **(X_test)**

In [14]:
# PREDICT the output using test data (X_test)
y_pred = regressor.predict(X_test)

In [15]:
# y_pred contains the results predicted by the model.
print(y_pred)

[431.28 459.59 460.06 ... 471.46 437.76 462.74]


# 3 - Evaluation

## Evaluating the model; **y_test ve y_pred**

In [16]:
# The outputs produced by the model (y_pred) and real values (y_test) are used.

# Evaluating the model
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.922905874177941